### ISSUE TITLE
Zone info not printed when listing using `scw ps -a`

### ISSUE THREAD

**Issue by bchatelard** [scaleway/scaleway-cli#466] opened 2017-06-15 08:23 UTC
Zone information are not displayed when listing stopped servers using `scw ps -a`.
They are only available using `scw ps`.

```
$ scw ps                                                                                                                        
SERVER ID           IMAGE                       ZONE                CREATED             STATUS              PORTS               NAME                 COMMERCIAL TYPE
07010ea0            Docker_1_12_2               par1                About an hour       running             212.47.231.91       cocky-shannon        VC1S

$ scw ps -a
SERVER ID           IMAGE                       ZONE                CREATED             STATUS              PORTS               NAME                      COMMERCIAL TYPE
b9b7c4c9            Ubuntu_Xenial_16_04_lates                       About an hour       stopped                                 loving-yonath             VC1S
e1d03a84            Ubuntu_Xenial_16_04_lates                       About an hour       stopped                                 stoic-mcnulty             VC1S
07010ea0            Docker_1_12_2               par1                About an hour       running             212.47.231.91       cocky-shannon             VC1S
```

**Comment by Nothing4You** [comment] 2017-10-08 14:34
Duplicate of #460

**Closed** 2018-04-17 14:36 UTC
