### ISSUE TITLE
add support for rdb instance metrics

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1234] opened 2020-07-15 14:21 UTC
## Description

Blocked by #1172 

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.4
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jerome-quere** [comment] 2020-07-15 16:06
Duplicate of #1161

**Closed by jerome-quere** 2020-07-15 16:06 UTC
Labels: database, enhancement
