### ISSUE TITLE
scaleway ps empty but server still alive on web console

### ISSUE THREAD

**Issue by suspended** [scaleway/scaleway-cli#540] opened 2019-02-27 06:54 UTC
I want to programatically shut down servers but it seems like the servers are still alive on the web console even though they disappear from the cli. What gives?

**Comment by QuentinBrosse** [comment] 2019-03-16 08:38
Hi @suspended,

I can't reproduce your issue. Does it still occur? If it is the case, could you please describe the steps to reproduce?

It is also possible that the problem comes from the console and not the CLI.

Thanks for reporting this issue ! :)

**Comment by remyleone** [comment] 2020-07-16 12:44
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

**Closed by remyleone** 2020-07-16 12:44 UTC
Labels: v1
