### ISSUE TITLE
Easier access to configuration values

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#977] opened 2020-05-01 11:43 UTC
Let's suppose that I want to get the region of my current configuration. Just the string of the region.
At the moment I can have it using:

`scw config get default_region -o json | jq -r ".[0].value"`

I would like to have something easier to use

### Description

`scw config get region`

### How I imagine scw could expose this functionality

`scw config get region`

This one is shorter than default_region
And more generally have shorter commands to get to the values. 
Having direct output as a string and not a table with the value could be useful

**Comment by jerome-quere** [comment] 2020-05-01 11:43
duplicate of  #948

**Closed** 2020-05-18 10:36 UTC
Labels: enhancement
